services:
  demo:
  kml:
  tms:
    # needs no arguments
  wms:
#    srs: ['EPSG:31287'] #,'EPSG:4326']
    srs: ['EPSG:31287','EPSG:4326']
    bbox_srs: ['EPSG:31287']
    image_formats: ['image/jpeg']
    md:
      # metadata used in capabilities documents
      title: MapProxy WMS Proxy
      abstract: This is the fantastic MapProxy.
      online_resource: http://mapproxy.org/
#
layers:
  - name: ortho
    title: Orthophoto
    sources: [ortho_cache]

caches:
  ortho_cache:
    sources: [ortho_wms]
    cache:
      type: mbtiles
      filename: /home/hannes/map_cache/austria_map.mbtiles

sources:
  ortho_wms:
    type: wms
    req:
      url: http://gis.lebensministerium.at/wmsgw/?
      layers: Orthophoto
      key: f4b35fcfaf22e69bf13c8c7dcae3da75
    wms_opts:
      version: 1.1.0
    coverage:
      bbox: [110000, 250000, 690000, 590000]
      bbox_srs: 'EPSG:31287'
    supported_srs: ['EPSG:31287'] #,'EPSG:4326']
    supported_formats: ['image/jpeg']
#    coverage:
 #     bbox: -1,-1,1000000,700000
  #    bbox_srs: 'EPSG:31287'


globals:
  # # coordinate transformation options
  srs:
  #   # WMS 1.3.0 requires all coordiates in the correct axis order,
  #   # i.e. lon/lat or lat/lon. Use the following settings to
  #   # explicitly set a CRS to either North/East or East/North
  #   # ordering.
  #   axis_order_ne: ['EPSG:9999', 'EPSG:9998']
  #   axis_order_en: ['EPSG:0000', 'EPSG:0001']
  #   # you can set the proj4 data dir here, if you need custom
  #   # epsg definitions. the path must contain a file named 'epsg'
  #   # the format of the file is:
  #   # <4326> +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs  <>
  #    proj_data_dir: '/myProj4defs'

  # # cache options
  cache:
    # where to store the cached images
    base_dir: './cache_data'
    # where to store lockfiles
    lock_dir: './cache_data/locks'
  #   # request x*y tiles in one step
  #   meta_size: [4, 4]
  #   # add a buffer on all sides (in pixel) when requesting
  #   # new images
  #   meta_buffer: 80


  # image/transformation options
  image:
#      resampling_method: nearest
      # resampling_method: bilinear
       resampling_method: bicubic
  #     jpeg_quality: 90
  #     # stretch cached images by this factor before
  #     # using the next level
  #     stretch_factor: 1.15
  #     # shrink cached images up to this factor before
  #     # returning an empty image (for the first level)
  #     max_shrink_factor: 4.0
